spring.application.name=ForoHub

# La URL puede usar una variable, y si no existe, usa la de tu máquina local
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/forohub_db}

# Driver de la base de datos
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Usuario de la base de datos
spring.datasource.username=${DB_USERNAME}

# Contraseña de la base de datos
spring.datasource.password=${DB_PASSWORD}

# Desactivar validación/creación de Hibernate
spring.jpa.hibernate.ddl-auto=none