INSERT INTO perfiles (rol)
SELECT 'ROLE_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM perfiles WHERE rol = 'ROLE_ADMIN');

INSERT INTO perfiles (rol)
SELECT 'ROLE_USER'
WHERE NOT EXISTS (SELECT 1 FROM perfiles WHERE rol = 'ROLE_USER');

INSERT INTO perfiles (rol)
SELECT 'ROLE_MODERADOR'
WHERE NOT EXISTS (SELECT 1 FROM perfiles WHERE rol = 'ROLE_MODERADOR');
